# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f06f43a1013bd4e8895a4a15f6820596"
name = "solar-combination"
handle = "solar-combination"
application_url = "https://acres-corporations-furnishings-degree.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-629da44c.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://acres-corporations-furnishings-degree.trycloudflare.com/auth/callback",
  "https://acres-corporations-furnishings-degree.trycloudflare.com/auth/shopify/callback",
  "https://acres-corporations-furnishings-degree.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://acres-corporations-furnishings-degree.trycloudflare.com"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
