# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a09c06b8d74e31fbcfe0ea426414e7e4"
application_url = "https://brothers-begins-forests-lights.trycloudflare.com"
embedded = true
name = "solar-combination-local"
handle = "solar-combination-local"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-629da44c.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://brothers-begins-forests-lights.trycloudflare.com/auth/callback",
  "https://brothers-begins-forests-lights.trycloudflare.com/auth/shopify/callback",
  "https://brothers-begins-forests-lights.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
