# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a09c06b8d74e31fbcfe0ea426414e7e4"
application_url = "https://workout-swing-yoga-nicole.trycloudflare.com"
embedded = true
name = "solar-combination-local"
handle = "solar-combination-local"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-629da44c.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_inventory,write_locations,write_orders,write_products"

[auth]
redirect_urls = [
  "https://workout-swing-yoga-nicole.trycloudflare.com/auth/callback",
  "https://workout-swing-yoga-nicole.trycloudflare.com/auth/shopify/callback",
  "https://workout-swing-yoga-nicole.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://workout-swing-yoga-nicole.trycloudflare.com"
subpath = "local"
prefix = "apps"

[pos]
embedded = false
